const express = require('express')
const app = express()
const env = require("dotenv")
env.config({ path: "./config/.env" })
const db = require("./config/db")
db()
const cors = require("cors")
app.use(express.json())
app.use(express.static("public"))
app.use(cors())
const user = require("./routes/bike-routes")
const signup = require("./routes/signup-routers")
const login = require("./routes/auth-routes")
const adminUser = require("./routes/admin-routes")
app.use("/api/v1", adminUser)
app.use("/api/v1", user)
app.use("/api/v1/signup", signup)
app.use("/api/v1", login)
app.listen(process.env.PORT, () => console.log(`Example app listening on port ${process.env.PORT}!`))